# Generated by Django 2.2.1 on 2021-07-20 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Сумма списания/пополнения'),
        ),
        migrations.AddField(
            model_name='pays',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pays',
            name='type_of_pays',
            field=models.CharField(choices=[('карта', 'Карта'), ('наличные', 'Наличные')], default='', max_length=255, verbose_name='Тип платежа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pays',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Описание платежа'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назначение платежа'),
        ),
    ]
