# Generated by Django 2.2.1 on 2021-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0002_auto_20210720_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], default='', max_length=255, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pays',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
