# Generated by Django 2.2.1 on 2022-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0002_tokenreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, choices=[('default.jpg', 'default.jpg'), ('man.jpeg', 'man.jpeg'), ('girl.jpg', 'girl.jpg')], default='default.jpg', max_length=100, null=True),
        ),
    ]
