# Generated by Django 2.2.1 on 2022-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0003_auto_20220228_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, choices=[('static/default.jpg', 'static/default.jpg'), ('static/man.jpeg', 'static/man.jpeg'), ('static/girl.jpg', 'static/girl.jpg')], default='static/default.jpg', max_length=100, null=True),
        ),
    ]
