# Generated by Django 2.2.1 on 2021-08-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0004_auto_20210809_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
