# Generated by Django 2.2.1 on 2021-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0006_auto_20210809_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='type_of_pays',
            field=models.CharField(choices=[('карта', 'Карта'), ('наличные', 'Наличные')], max_length=255, verbose_name='Тип платежа'),
        ),
    ]
