# Generated by Django 2.2.1 on 2021-08-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0007_auto_20210814_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
    ]
