# Generated by Django 2.2.1 on 2021-09-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0009_notes_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_send',
            field=models.BooleanField(default=False),
        ),
    ]
