# Generated by Django 2.2.1 on 2021-09-26 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0012_auto_20210925_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='body_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Тело шаблона'),
        ),
    ]
