# Generated by Django 2.2.1 on 2022-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0016_auto_20220129_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='type_of_pays',
            field=models.CharField(choices=[('карта', 'Карта'), ('наличные', 'Наличные')], max_length=255, verbose_name='Тип платежа'),
        ),
    ]
