version: '3.7'

services:
  web:
    build: ./
    container_name: citadel_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: citadel_db
    volumes:
      - citadel_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    container_name: citadel_nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/static
      - ./media:/media
      - ./ssl:/ssl
    depends_on:
      - web

volumes:
  citadel_data: